[build]
  command = "npm run build"
  publish = "build"
  environment = { SECRETS_SCAN_OMIT_KEYS = "REACT_APP_BASKETBALL_API_HOST,REACT_APP_FOOTBALL_API_KEY,REACT_APP_NEWS_API_KEY,REACT_APP_TENNIS_API_HOST,REACT_APP_TENNIS_API_KEY,REACT_APP_CRICKET_API_KEY,REACT_APP_BASKETBALL_API_KEY,REACT_APP_FOOTBALL_API_HOST,REACT_APP_CRICKET_API_HOST" }

[functions]
  directory = "netlify/functions" # Specify the directory where your Netlify Functions are located

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
