[build]
  command = "npm run build"
  publish = "build"
  environment = { NODE_VERSION = "18.20.4", SECRETS_SCAN_ENABLED = "false" }

[functions]
  directory = "netlify/functions" # Specify the directory where your Netlify Functions are located

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
